apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-only-role-binding
  namespace: default
subjects:
- kind: Group
  name: admin
roleRef:
  kind: ClusterRole
  name: full-access-clusterrole
  apiGroup: rbac.authorization.k8s.io

