apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::891377147533:role/staging-demo-eks-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - admin
      rolearn: arn:aws:iam::891377147533:role/staging-demo-eks-admin
      username: manager
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::891377147533:role/staging-demo-eks-nodes\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - admin\n  rolearn: arn:aws:iam::891377147533:user/manager\n  username: manager\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-06-28T05:38:11Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"865","uid":"44905de8-7ba6-438d-a94a-38a3f46a105c"}}
  creationTimestamp: "2024-06-28T05:38:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "11647"
  uid: 44905de8-7ba6-438d-a94a-38a3f46a105c
